[project]
name = "schemati"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "databricks-sdk>=0.57.0",
    "pydantic>=2.11.7",
]
