name: Validate Workflows

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate workflow files
      run: |
        # Check for syntax errors in workflow files
        for file in .github/workflows/*.yml .github/workflows/*.yaml; do
          if [ -f "$file" ]; then
            echo "Validating $file"
            python -c "import yaml; yaml.safe_load(open('$file'))" || exit 1
          fi
        done
        echo "All workflow files are valid YAML"